# Generated by Django 6.1 on 2026-08-27 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='box_images/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_available', models.BooleanField(default=True)),
                ('box_type', models.CharField(choices=[('print', 'Print Box'), ('package', 'Package Storage Box'), ('combined', 'Combined (Print & Package Storage)')], max_length=20)),
                ('printing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stored_print_hourly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dropbox_pricing', models.JSONField(blank=True, help_text='{"small": 2.5, "medium": 5.0, "large": 8.0}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('summary', 'Summary'), ('cost_review', 'Cost Review'), ('payment', 'Payment'), ('active_storage', 'Active Storage'), ('completed', 'Completed')], default='summary', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_code', models.CharField(max_length=50, unique=True)),
                ('user_type', models.CharField(default='supervisee', max_length=20)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('system', 'System'), ('user', 'User')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('summary', 'Summary'), ('payment', 'Payment'), ('status', 'Status'), ('action', 'Action')], default='text', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='new_backend.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cubby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('cubby_type', models.CharField(choices=[('small', 'Small Package Cubby'), ('medium', 'Medium Package Cubby'), ('large', 'Large Package Cubby'), ('print', 'Stored Print Cubby'), ('universal', 'Universal Instant Print Cubby')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubbies', to='new_backend.box')),
            ],
            options={
                'ordering': ['box', 'code'],
                'unique_together': {('box', 'code')},
            },
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='cubby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='new_backend.cubby'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Naira', max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_sent', models.BooleanField(default=False, help_text='True if the 2-hour warning has been triggered')),
                ('task_type', models.CharField(choices=[('instant_print', 'Instant Print (Standby)'), ('stored_print', 'Stored Print (Pigeonhole)'), ('drop', 'Drop Box Storage')], max_length=20)),
                ('drop_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in hours for stored_print, or days for drop', null=True)),
                ('orientation', models.CharField(blank=True, choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], max_length=20, null=True)),
                ('pages_per_sheet', models.CharField(blank=True, choices=[('front_only', 'Front Only'), ('front_and_back', 'Front & Back')], max_length=30, null=True)),
                ('color', models.CharField(blank=True, choices=[('black_and_white', 'Black & White'), ('colored', 'Colored')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid & Ready for Drop/Print'), ('active', 'Item Stored / Printing in Progress'), ('completed', 'Completed & Retrieved'), ('overstayed', 'Overstayed (Admin Action Required)'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='print_jobs/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('unlock_code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='new_backend.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Box/System Bot')], max_length=10)),
                ('text', models.TextField()),
                ('action_taken', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='new_backend.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='new_backend.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pigeonhole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Hole A', 'Locker 1', 'Universal'", max_length=50)),
                ('size', models.CharField(choices=[('universal', 'Universal (Instant Print)'), ('small', 'Small Dropbox'), ('medium', 'Medium Dropbox'), ('large', 'Large Dropbox'), ('print_storage', 'Print Storage (Stored Printing)')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigeonholes', to='new_backend.box')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pigeonhole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='new_backend.pigeonhole'),
        ),
        migrations.CreateModel(
            name='PrivateBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_box', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCubby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cubby', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='private_assignment', to='new_backend.cubby')),
                ('private_box', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cubby', to='new_backend.privatebox')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCubbyActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cubby_created', 'Cubby created'), ('pin_changed', 'PIN changed'), ('package_deposited', 'Package deposited'), ('package_picked_up', 'Package picked up'), ('temp_pin_created', 'Temporary PIN created'), ('temp_pin_used', 'Temporary PIN used'), ('temp_pin_revoked', 'Temporary PIN revoked'), ('access_shared', 'Access shared'), ('access_revoked', 'Access revoked'), ('owner_access', 'Owner accessed cubby'), ('shared_user_access', 'Shared user accessed cubby')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('private_cubby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='new_backend.privatecubby')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateCubbyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_cubby_applications', to='new_backend.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_cubby_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCubbyTemporaryPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('one_time', models.BooleanField(default=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('private_cubby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_pins', to='new_backend.privatecubby')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('instant_print', 'Instant Print'), ('stored_print', 'Stored Print'), ('package_storage', 'Package Storage')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active Storage'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_until', models.DateTimeField(blank=True, null=True)),
                ('unlock_password', models.CharField(blank=True, max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('visible_until', models.DateTimeField(blank=True, null=True)),
                ('task_data', models.JSONField(blank=True, default=dict, help_text='Stores task-specific details such as printing options or package storage selections.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='new_backend.box')),
                ('cubby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='new_backend.cubby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='new_backend.task'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('payment', 'Task Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='new_backend.task')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='new_backend.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateCubbySharedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('deposit_only', 'Deposit only'), ('pickup_only', 'Pickup only'), ('full_access', 'Full access')], default='full_access', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubby_access_granted', to=settings.AUTH_USER_MODEL)),
                ('private_cubby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_accesses', to='new_backend.privatecubby')),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubby_access_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('private_cubby', 'shared_user')},
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('cubby',), name='one_active_task_per_cubby'),
        ),
    ]
