# Generated by Django 6.1 on 2026-08-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='box',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pigeonhole',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pigeonhole',
            name='box',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Pigeonhole',
        ),
    ]
