# Generated by Django 6.1 on 2026-08-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0002_remove_order_box_remove_order_pigeonhole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='box_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('queued', 'Queued'), ('received', 'Received'), ('processing', 'Processing'), ('printing', 'Printing'), ('waiting_for_deposit', 'Waiting for Deposit'), ('package_stored', 'Package Stored'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_sent', max_length=30),
        ),
    ]
