# Generated by Django 6.1 on 2026-09-01 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0004_task_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='unlock_password',
            new_name='access_code',
        ),
        migrations.CreateModel(
            name='PrintDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('print_settings', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='new_backend.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
