# Generated by Django 6.1 on 2026-09-02 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0005_rename_unlock_password_task_access_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/documents/')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('print_settings', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='one_active_task_per_cubby',
        ),
        migrations.AlterField(
            model_name='printdocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_documents', to='new_backend.task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('cubby__isnull', False), ('status', 'active')), fields=('cubby',), name='one_active_task_per_cubby'),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='new_backend.task'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
    ]
