# Generated by Django 6.1 on 2026-09-02 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0006_taskdocument_remove_task_one_active_task_per_cubby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printdocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='new_backend.task'),
        ),
    ]
