# Generated by Django 6.1 on 2026-09-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0007_alter_printdocument_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('summary', 'Summary'), ('cost_review', 'Cost Review'), ('payment', 'Payment'), ('active_print', 'Active Print'), ('active_storage', 'Active Storage'), ('completed', 'Completed')], default='summary', max_length=30),
        ),
    ]
