# Generated by Django 6.1 on 2026-09-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0008_alter_conversationsession_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='printdocument',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
