# Generated by Django 6.1 on 2026-09-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0009_printdocument_storage_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDocument',
        ),
    ]
