# Generated by Django 6.1 on 2026-09-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0010_delete_taskdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('summary', 'Summary'), ('cost_review', 'Cost Review'), ('document_review', 'Document Review'), ('payment', 'Payment'), ('active_print', 'Active Print'), ('active_storage', 'Active Storage'), ('completed', 'Completed')], default='summary', max_length=30),
        ),
        migrations.CreateModel(
            name='PendingPrintDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/pending_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('print_settings', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_documents', to='new_backend.task')),
            ],
        ),
    ]
