# Generated by Django 6.1 on 2026-09-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0011_alter_conversationsession_current_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('summary', 'Summary'), ('cost_review', 'Cost Review'), ('document_review', 'Document Review'), ('extension_review', 'Extension Review'), ('payment', 'Payment'), ('active_print', 'Active Print'), ('active_storage', 'Active Storage'), ('completed', 'Completed')], default='summary', max_length=30),
        ),
    ]
