# Generated by Django 6.1 on 2026-09-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0012_alter_conversationsession_current_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAccessShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_shares', to='new_backend.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
