# Generated by Django 6.1 on 2026-09-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0013_packageaccessshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageaccessshare',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
