# Generated by Django 6.1 on 2026-09-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0015_globalpricing_alter_task_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='cubby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='new_backend.cubby'),
        ),
    ]
