# Generated by Django 6.1 on 2026-09-05 14:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_backend', '0016_alter_conversationsession_cubby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpricing',
            name='instant_print_price_per_page',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
